Avatar
MuratovER/ts pull request #93
Opened 2021-03-17 17:04 UTC by MuratovER

Created logic for upload and unload of a profile avatar

2021-03-17 20:40 UTC, nurgalive requested changes

2021-03-17 20:40 UTC, nurgalive commented on mainsite/views.py
> +    form = PhotoForm(instance=image_blank)
Думаю, что это строка кода лишняя

2021-03-17 20:40 UTC, nurgalive commented on mainsite/views.py
> +    image_blank = Profile.objects.get(pk=1)
Пользователь указан явно по id

2021-03-17 20:40 UTC, nurgalive commented on mainsite/templates/mainsite/user_page.html
> +            {% cloudinary profile.image format="jpg" width=223 height=223 crop="fill"  %}
Отлично, оказывается нужно было использовать специальный тэг

2021-03-18 10:23 UTC, nurgalive requested changes

2021-03-18 10:23 UTC, nurgalive commented on mainsite/views.py
> +    context = dict(backend_form = PhotoForm(instance=image_blank))
Переменной ```instance``` присваивается значение пременной, которая еще не создана.
Не уверен, что этот код рабочий.

2021-03-18 10:23 UTC, nurgalive commented on mainsite/views.py
> +            form = PhotoForm(instance=image_blank)
Переменная ```form``` нигде в не используется потом

2021-03-18 10:23 UTC, nurgalive commented on mainsite/views.py
> +            image_blank = Profile.objects.get(pk=1)
Для загрузки ищешь пользователя по ID, а должен быть текущий пользователь.
Иначе любой пользователь будет менять аватарку только админу.

Название переменной ```image_blank``` не отражает сути того, что в ней находится.
Что-нибудь типа ```user_object``` или ```user_profile``` или просто ```user``` подойдёт лучше. Потому что в этой переменной хранится объект типа Profile. Мы его передаём в форму, потому что в форме мы хотим поменять одно поле  ```image``` этого объекта.

2021-03-18 12:23 UTC, MuratovER commented on mainsite/views.py
> +            form = PhotoForm(instance=image_blank)
Разве form не используется для сохранения?

2021-03-18 20:27 UTC, nurgalive commented on mainsite/views.py
> +            form = PhotoForm(instance=image_blank)
Да, верно

2021-03-18 20:29 UTC, nurgalive commented on mainsite/views.py
> +            form = PhotoForm(instance=image_blank)
Посмотрел старый рабочий код. Что-то мы сильно нагородили тут. Посмотри старый вид функции, которая работала, и доработай её так, чтобы она так же заработала тут.

https://github.com/MuratovER/ts/blob/63be432c517bc8d0b3594c0ba4b041de7585df44/mainsite/views.py#L338

2021-03-18 20:36 UTC, nurgalive requested changes

2021-03-18 20:36 UTC, nurgalive commented on mainsite/admin.py
> +from .models import Post, Skill, UserSkill, Profile, Difficulty, Sphere_of_life, Achivement, UserAchivement, User_affirmation, Comment,
Запятой в конце быть не должно

2021-03-18 20:36 UTC, nurgalive commented on mainsite/templates/mainsite/load.html
> +
Название файлы load.html не раскрывает фунции, которую выполняет страница. Она загружает файлы на компьютер? Загружает процессор компьютера?

2021-03-18 20:36 UTC, nurgalive commented on mainsite/templates/mainsite/load.html
> +      <!-- {{ form.image }} -->
Эту строку можно удалить.

2021-03-18 20:36 UTC, nurgalive commented on mainsite/templates/mainsite/user_page.html
> +            {% cloudinary profile.image format="jpg" width=223 height=223 crop="fill"  %}
Снова посмотрел старый код, его версия подходила лучше, потому что использовала css стиль для отображения аватарки. Стоит вернуть старый вариант. А в ```alt``` прописать ```profile-avatar```
https://github.com/MuratovER/ts/blob/63be432c517bc8d0b3594c0ba4b041de7585df44/mainsite/templates/mainsite/user_page.html#L21

2021-03-18 20:36 UTC, nurgalive commented on mainsite/views.py
> +from .models import Post, Skill, UserSkill, Profile, Sphere_of_life, Achivement, UserAchivement, User_affirmation, Comment,
Нужно убрать запятую в конце.

2021-03-18 20:37 UTC, nurgalive commented on mainsite/templates/mainsite/user_page.html
> +            {% cloudinary profile.image format="jpg" width=223 height=223 crop="fill"  %}
Самой собой его надо немного подредактировать.

2021-03-19 06:03 UTC, MuratovER commented on mainsite/templates/mainsite/user_page.html
> +            {% cloudinary profile.image format="jpg" width=223 height=223 crop="fill"  %}
Оно не отображается если делать так  <img src='{{ profile_picture.image.url }}' class='header-profile-img' alt="">

2021-03-19 06:03 UTC, MuratovER commented on mainsite/templates/mainsite/user_page.html
> +            {% cloudinary profile.image format="jpg" width=223 height=223 crop="fill"  %}
Я уже локально пытался
и дентсввенный способ тегом оставался

2021-03-20 05:09 UTC, MuratovER commented on mainsite/templates/mainsite/user_page.html
> +            {% cloudinary profile.image format="jpg" width=223 height=223 crop="fill"  %}
<img src='{% cloudinary profile.image format="jpg" width=223 height=223 crop="fill"  %}' class='header-profile-img' alt="">

2021-03-20 05:09 UTC, MuratovER commented on mainsite/templates/mainsite/user_page.html
> +            {% cloudinary profile.image format="jpg" width=223 height=223 crop="fill"  %}
Делал так `<img src='{% cloudinary profile.image format="jpg" width=223 height=223 crop="fill"  %}' class='header-profile-img' alt=""> `

2021-03-26 06:02 UTC, nurgalive requested changes

2021-03-26 07:00 UTC, merged